
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class admin extends javax.swing.JFrame {
    
    Connection con=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    /**
     * Creates new form admin
     */
    public admin() {
        initComponents();
        
        try{
           Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        
            String url="jdbc:sqlserver://localhost:1433;databaseName=userloginproject;user=sa;password=shawon420";
            con=DriverManager.getConnection(url); 
        }
        catch(Exception e){
            e.printStackTrace();
        }
        printmessege();
    }
    void printmessege(){
        try{ 
            String sql ="Select COUNT(roll) from messeg_table where bool='1'";
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                String sum=rs.getString(1);
                if(sum.equals("0")){
                    messege_button.setText("");
                }
                else
                    messege_button.setText(sum);
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        birthdate = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        department = new javax.swing.JComboBox<>();
        semester = new javax.swing.JComboBox<>();
        messege_button = new javax.swing.JButton();
        section = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        email = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        imagelabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(570, 600));
        setMinimumSize(new java.awt.Dimension(570, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/info_icon.png"))); // NOI18N
        jLabel1.setText("Admin's Control");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Student's id:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Student's name:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 100, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Date of birth:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 80, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Contact No:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 70, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Address:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 50, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Semester:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 60, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Section:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 50, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Department:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 80, -1));

        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idKeyReleased(evt);
            }
        });
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 160, 30));
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 161, -1));
        getContentPane().add(birthdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 161, -1));
        getContentPane().add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 161, -1));
        getContentPane().add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 161, -1));

        department.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Civil", "EEE", "CSE", "MPE", "Architecture", "Textile", "BBA" }));
        department.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentActionPerformed(evt);
            }
        });
        getContentPane().add(department, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 161, -1));

        semester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1/1", "1/2", "2/1", "2/2", "3/1", "3/2", "4/1", "4/2" }));
        getContentPane().add(semester, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 161, -1));

        messege_button.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        messege_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/messege_icon.png"))); // NOI18N
        messege_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messege_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(messege_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 108, 43));

        section.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D" }));
        section.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sectionActionPerformed(evt);
            }
        });
        getContentPane().add(section, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, 161, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Gender:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 50, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/power_off.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, -1, -1));

        buttonGroup1.add(male);
        male.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        male.setForeground(new java.awt.Color(0, 0, 204));
        male.setText("MALE");
        getContentPane().add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 60, -1));

        buttonGroup1.add(female);
        female.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        female.setForeground(new java.awt.Color(0, 0, 204));
        female.setText("FEMALE");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        getContentPane().add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 70, -1));
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 161, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("E-Mail Address:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 90, -1));

        jLabel13.setText("example:15.01.01.001");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 140, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/update icon.png"))); // NOI18N
        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 305, -1, 36));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/erase-128.png"))); // NOI18N
        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 403, 87, 33));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete_16x16.gif"))); // NOI18N
        jButton5.setText("Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 352, 87, 35));

        jDesktopPane1.setMaximumSize(new java.awt.Dimension(128, 128));
        jDesktopPane1.setMinimumSize(new java.awt.Dimension(128, 128));

        imagelabel.setBackground(new java.awt.Color(0, 0, 0));
        imagelabel.setText("               Image");
        imagelabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        imagelabel.setAlignmentX(1.0F);
        imagelabel.setAlignmentY(2.0F);
        imagelabel.setMaximumSize(new java.awt.Dimension(128, 128));
        imagelabel.setMinimumSize(new java.awt.Dimension(128, 128));
        imagelabel.setPreferredSize(new java.awt.Dimension(128, 128));

        jDesktopPane1.setLayer(imagelabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 128, Short.MAX_VALUE)
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(imagelabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 128, Short.MAX_VALUE)
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(imagelabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 141, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/form_back2.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void departmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departmentActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_femaleActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to update?","Update Record",JOptionPane.YES_NO_OPTION);
        if(p==0){
           
            try{
                String selected_roll=id.getText();
                String value1 = name.getText();
                String value2 = birthdate.getText();
                male.setActionCommand("Male");
                female.setActionCommand("Female");
                String value3 = buttonGroup1.getSelection().getActionCommand();
                String value4 = contact.getText();
                String value5 = email.getText();
                String value6 = address.getText();
                String value7 = department.getSelectedItem().toString();
                String value9 = semester.getSelectedItem().toString();
                String value10 = section.getSelectedItem().toString();


                String sql= "update information set roll='"+selected_roll+"',name='"+value1+"', birthdate='"+value2+"', "
                        + "gender='"+value3+"',contact='"+value4+"',email='"+value5+"',address='"+value6+"',department= '"+value7+"', "
                        + "semester='"+value9+"',section ='"+value10+"'"
                        + "where roll='"+selected_roll+"' ";

                pst=con.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Record Updated");

            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        id.setText("");
        name.setText("");
        birthdate.setText("");
        buttonGroup1.clearSelection();
        contact.setText("");
        email.setText("");
        address.setText("");
        department.setSelectedIndex(0);
        semester.setSelectedIndex(0);
        section.setSelectedIndex(0);
        imagelabel.setIcon(null);
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete?","Delete Record",JOptionPane.YES_NO_OPTION);
        if(p==0){
            String sql ="delete from information where roll=? ";
               try{
                    pst=con.prepareStatement(sql);
                    pst.setString(1, id.getText());
                    pst.execute();

                    JOptionPane.showMessageDialog(null,"Record Deleted");
                    name.setText("");
                    birthdate.setText("");
                    buttonGroup1.clearSelection();
                    contact.setText("");
                    email.setText("");
                    address.setText("");
                    department.setSelectedIndex(0);
                    semester.setSelectedIndex(0);
                    section.setSelectedIndex(0);
                    imagelabel.setIcon(null);
                   

               }catch(Exception e){

                   JOptionPane.showMessageDialog(null, e);
               }finally {

                   try{
                       rs.close();
                       pst.close();

                   }
                   catch(Exception e){
                       e.printStackTrace();
                   }
               }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyReleased
        // TODO add your handling code here:
        try{   
            String sql ="select * from information where roll='"+id.getText()+ "'";
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                String add1 =rs.getString("roll");
                id.setText(add1);

                String add2 =rs.getString("name");
                name.setText(add2);


                String add4 =rs.getString("birthdate");
                birthdate.setText(add4);

                String add5 =rs.getString("gender");
                if(add5.equals("Male"))
                    male.setSelected(true);
                else
                    female.setSelected(true);

                String add6 =rs.getString("contact");
                contact.setText(add6);

                String add7 =rs.getString("email");
                email.setText(add7);

                String add8 =rs.getString("address");
                address.setText(add8);

                String add9 =rs.getString("department");
                //Civil, EEE, CSE, MPE, Architecture, Textile, BBA
                if(add9.equals("Civil"))
                    department.setSelectedIndex(0);
                else if(add9.equals("EEE"))
                    department.setSelectedIndex(1);
                else if(add9.equals("CSE"))
                    department.setSelectedIndex(2);    
                else if(add9.equals("MPE"))
                    department.setSelectedIndex(3);    
                else if(add9.equals("Architecture"))
                    department.setSelectedIndex(4);    
                else if(add9.equals("Textile"))
                    department.setSelectedIndex(5);
                else if(add9.equals("BBA"))
                    department.setSelectedIndex(6);

                String add10 =rs.getString("semester");
                if(add10.equals("1.1"))
                    semester.setSelectedIndex(0);
                else if(add10.equals("1.2"))
                    semester.setSelectedIndex(1);
                else if(add10.equals("2.1"))
                    semester.setSelectedIndex(2);
                else if(add10.equals("2.2"))
                    semester.setSelectedIndex(3);
                else if(add10.equals("3.1"))
                    semester.setSelectedIndex(4);
                else if(add10.equals("3.2"))
                    semester.setSelectedIndex(5);
                else if(add10.equals("4.1"))
                    semester.setSelectedIndex(6);
                else if(add10.equals("4.2"))
                    semester.setSelectedIndex(7);

                String add11 =rs.getString("section");
                if(add11.equals("A"))
                    section.setSelectedIndex(0);
                else if(add11.equals("B"))
                    section.setSelectedIndex(1);
                else if(add11.equals("C"))
                    section.setSelectedIndex(2);
                else if(add11.equals("D"))
                    section.setSelectedIndex(3);


                byte[] img = rs.getBytes("image");
                ImageIcon imageIcon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(imagelabel.getWidth(), imagelabel.getHeight(), Image.SCALE_SMOOTH));
                imagelabel.setIcon(imageIcon);
            
            
            }
            else{
                //id.setText("");
                name.setText("");
                birthdate.setText("");
                buttonGroup1.clearSelection();
                contact.setText("");
                email.setText("");
                address.setText("");
                department.setSelectedIndex(0);
                semester.setSelectedIndex(0);
                section.setSelectedIndex(0);
                imagelabel.setIcon(null);
            }
        }
         catch(Exception e){
             e.printStackTrace();
         }
    }//GEN-LAST:event_idKeyReleased

    private void messege_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messege_buttonActionPerformed
        // TODO add your handling code here:
        
        messege_table mu=new messege_table();
        this.setVisible(false);
        mu.setVisible(true);
        
    }//GEN-LAST:event_messege_buttonActionPerformed

    private void sectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sectionActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JTextField birthdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField contact;
    private javax.swing.JComboBox<String> department;
    private javax.swing.JTextField email;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField id;
    private javax.swing.JLabel imagelabel;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton male;
    private javax.swing.JButton messege_button;
    private javax.swing.JTextField name;
    private javax.swing.JComboBox<String> section;
    private javax.swing.JComboBox<String> semester;
    // End of variables declaration//GEN-END:variables
}
