
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class messege_user extends javax.swing.JFrame {

    /**
     * Creates new form messege_user
     */
    String loginid;
    Connection con=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    public messege_user() {
        initComponents();
    }
    public messege_user(String ids){
        initComponents();
        loginid=ids;
        printid();
        connection();
        notification();
        
    }
    final void printid(){
        idnumber.setText("ID: "+loginid);
    }
    void connection(){
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=userloginproject;user=sa;password=shawon420";
            con=DriverManager.getConnection(url);
        }
        catch(Exception e){
            e.printStackTrace();
        }
            
    }
    void notification(){
        try{    
            String sql ="select count(roll) from messege_table2 where roll='"+loginid+ "' and bool='1'";
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                String sum=rs.getString(1);
                if(sum.equals("0")){
                    messege_button.setText("");
                }
                else
                    messege_button.setText(sum);
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        idnumber = new javax.swing.JLabel();
        messege_button = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        messege_box = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 350));
        setMinimumSize(new java.awt.Dimension(500, 350));
        setPreferredSize(new java.awt.Dimension(500, 350));
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/messege_icon.png"))); // NOI18N
        jLabel3.setText("Messaging with Authority");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 10, 310, 35);
        getContentPane().add(idnumber);
        idnumber.setBounds(50, 70, 140, 20);

        messege_button.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        messege_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/messege_icon.png"))); // NOI18N
        messege_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messege_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(messege_button);
        messege_button.setBounds(280, 60, 108, 43);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/power_off.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(30, 200, 60, 70);

        jButton1.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/if_JD-10_2252355.png"))); // NOI18N
        jButton1.setText("Send Message");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(210, 230, 179, 38);

        messege_box.setColumns(20);
        messege_box.setRows(5);
        jScrollPane1.setViewportView(messege_box);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(150, 120, 240, 96);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bk4.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 500, 350);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=userloginproject;user=sa;password=shawon420";
            con=DriverManager.getConnection(url);
            String query="insert into messeg_table (roll,messege,bool) values (?,?,?)";
            PreparedStatement pst =con.prepareStatement(query);
            if(messege_box.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Write a messege to send");
            }
            else{
                pst.setString(1, loginid);
                pst.setString(2, messege_box.getText());
                pst.setInt(3,1);
                pst.execute();
                pst.close();
                JOptionPane.showMessageDialog(null, "Message sent");
                messege_box.setText("");
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void messege_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messege_buttonActionPerformed
        // TODO add your handling code here:
        showingmessege sh =new showingmessege(loginid);
        this.setVisible(false);
        sh.setVisible(true);

    }//GEN-LAST:event_messege_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(messege_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(messege_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(messege_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(messege_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new messege_user().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel idnumber;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea messege_box;
    private javax.swing.JButton messege_button;
    // End of variables declaration//GEN-END:variables
}
