
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class messege_table extends javax.swing.JFrame {

    /**
     * Creates new form messege_table
     */
    String rollnumber;
    Connection con;
    PreparedStatement pst=null;
    public messege_table() {
        initComponents();
        connection();
        show_table();
        messeaged();
    }
    
    
    public ArrayList<User> getUserList()
    {
        ArrayList<User> usersList = new ArrayList<User>();
        String sql="select * from messeg_table";
        try{
            Statement pst =con.createStatement();
            ResultSet rs=pst.executeQuery(sql);
            User user;

           while(rs.next())
           {
               user = new User(rs.getInt("serial"),rs.getString("roll"),rs.getString("messege"));
               usersList.add(user);
           }

        } 
        catch (Exception e) {
           e.printStackTrace();
        }
        return usersList;
    }
    
    public void show_table(){
        ArrayList<User> list=getUserList();
        DefaultTableModel model=(DefaultTableModel)table.getModel();
        Object[] row = new Object[3];
        for(int i=0;i<list.size();i++){
            row[0]=list.get(i).getserial();
            row[1]=list.get(i).getRoll();
            row[2]=list.get(i).getMessege();
            model.addRow(row);
        }
    }
       
    void connection(){
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=userloginproject;user=sa;password=shawon420";
            con=DriverManager.getConnection(url);
        }
        catch(Exception e){
            e.printStackTrace();
        }
            
    }
    void messeaged(){
        try{    
            String sql4 ="select * from messeg_table where bool='1'";
            PreparedStatement pst4=con.prepareStatement(sql4);
            ResultSet rs4=pst4.executeQuery();
            if(rs4.next()){
                String add=rs4.getString("messege");
                area.setText(add);
                id.setText(rs4.getString("serial"));
                rollnumber=rs4.getString("roll");
                roll_field.setText(rollnumber);
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
        try{    
            String sql1 ="update messeg_table set bool='0'";
            pst=con.prepareStatement(sql1);
            pst.execute();
            
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        reply = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        roll_field = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(550, 430));
        setMinimumSize(new java.awt.Dimension(550, 430));
        setPreferredSize(new java.awt.Dimension(540, 430));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial", "Roll", "Messege"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 250, 223));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 80, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Message:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Message Serial:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idKeyReleased(evt);
            }
        });
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 120, -1));

        area.setColumns(20);
        area.setRows(5);
        area.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                areaKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(area);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 220, 120));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/messege_icon.png"))); // NOI18N
        jLabel3.setText("Messages");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 168, 35));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 78, 38));

        reply.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        reply.setText("Send");
        reply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replyActionPerformed(evt);
            }
        });
        getContentPane().add(reply, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 80, 38));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Roll no:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        roll_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roll_fieldActionPerformed(evt);
            }
        });
        getContentPane().add(roll_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 120, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bk4.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void areaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_areaKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_areaKeyReleased

    private void idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyReleased
        // TODO add your handling code here:
        String sql ="select * from messeg_table where serial='"+id.getText()+ "'";
        try{    
            PreparedStatement pst1=con.prepareStatement(sql);
            ResultSet rs1= pst1.executeQuery();
            if(rs1.next()){
                String add=rs1.getString("messege");
                rollnumber=rs1.getString("roll");
                area.setText(add);
                roll_field.setText(rollnumber);
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_idKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        area.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void replyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replyActionPerformed
        // TODO add your handling code here:
        PreparedStatement pst=null;
        try{
            String query="insert into messege_table2 (roll,messege,bool) values (?,?,?)";
            pst =con.prepareStatement(query);
            if(area.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Write a messege to send");
            }
            if(!roll_field.getText().isEmpty()){
                pst.setString(1, roll_field.getText());
                pst.setString(2, area.getText());
                pst.setInt(3, 1);
                pst.execute();
                pst.close();
                JOptionPane.showMessageDialog(null, "Message sent");
                area.setText("");
            }
            else{
                String sql="select * from logindata";
                try{
                    Statement pst5 =con.createStatement();
                    ResultSet rs5=pst5.executeQuery(sql);

                    while(rs5.next())
                    {
                         pst.setString(1, rs5.getString("roll"));
                         pst.setString(2, area.getText());
                         pst.setInt(3, 1);
                         pst.execute();
                         //pst.close();


                    }
                    JOptionPane.showMessageDialog(null, "Message sent");
                    area.setText("");

                } 
                catch (Exception e) {
                   e.printStackTrace();
                }
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_replyActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        admin ad=new admin();
        this.setVisible(false);
        ad.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void roll_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roll_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roll_fieldActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(messege_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(messege_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(messege_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(messege_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new messege_table().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton reply;
    private javax.swing.JTextField roll_field;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
