
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class showingmessege extends javax.swing.JFrame {

    /**
     * Creates new form showingmessege
     */
    String loginid;
    Connection con=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    public showingmessege() {
        initComponents();
        connection();
        messeges();
    }
     public showingmessege(String number) {
        loginid=number;
        
        initComponents();
        connection();
        messeges();
        show_table();
    }
    void connection(){
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=userloginproject;user=sa;password=shawon420";
            con=DriverManager.getConnection(url);
        }
        catch(Exception e){
            e.printStackTrace();
        }
            
    }
     public ArrayList<User2> getUserList()
    {
        ArrayList<User2> usersList = new ArrayList<User2>();
        String sql="select * from messege_table2 where roll='"+loginid+"'";
        try{
            Statement pst1 =con.createStatement();
            ResultSet rs1=pst1.executeQuery(sql);
            User2 user;

           while(rs1.next())
           {
               user = new User2(rs1.getInt("serial"),rs1.getString("messege"));
               usersList.add(user);
           }

        } 
        catch (Exception e) {
           e.printStackTrace();
        }
        return usersList;
    }
    
    public void show_table(){
        ArrayList<User2> list=getUserList();
        DefaultTableModel model=(DefaultTableModel)table.getModel();
        Object[] row = new Object[2];
        for(int i=0;i<list.size();i++){
            row[0]=list.get(i).getserial();
            row[1]=list.get(i).getMessege();
            model.addRow(row);
        }
    }
       
    
    void messeges(){
        try{    
            String sql ="select * from messege_table2 where roll='"+loginid+ "' and bool='"+"1'";
            System.out.println(loginid);
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                String add=rs.getString("messege");
                messege.setText(add);
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
        try{    
            String sql1 ="update messege_table2 set bool='"+0+"' where roll='"+loginid+ "'";
            pst=con.prepareStatement(sql1);
            pst.execute();
            
        }
        catch(Exception e){
            e.printStackTrace();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        serialnum = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        messege = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 350));
        setMinimumSize(new java.awt.Dimension(500, 350));
        setPreferredSize(new java.awt.Dimension(500, 350));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        serialnum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                serialnumKeyReleased(evt);
            }
        });
        getContentPane().add(serialnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 100, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Serial:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 40, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial", "Messege"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(table);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 229, 223));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 51));
        jLabel1.setText("Messages from Authority");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 230, -1));

        messege.setColumns(20);
        messege.setRows(5);
        jScrollPane1.setViewportView(messege);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 230, 158));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 274, 80, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/message_back.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        messege_user mu=new messege_user(loginid);
        this.setVisible(false);
        mu.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void serialnumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_serialnumKeyReleased
        // TODO add your handling code here:
        String sql ="select * from messege_table2 where serial='"+serialnum.getText()+ "'";
        try{    
            PreparedStatement pst1=con.prepareStatement(sql);
            ResultSet rs1= pst1.executeQuery();
            if(rs1.next()){
                String add=rs1.getString("messege");
                messege.setText(add);
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_serialnumKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(showingmessege.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(showingmessege.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(showingmessege.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(showingmessege.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new showingmessege().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea messege;
    private javax.swing.JTextField serialnum;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
